# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'type: bug fix':
    include:
      - '^fix:'
    exclude: [ ]
  'type: chore':
    include:
      - '^chore:'
    exclude:
      - [ ]
  'type: documentation':
    include:
      - '^docs:'
    exclude: [ ]
  'type: improvemnet':
    include:
      - '^refactor:'
    exclude: [ ]
  'type: new feature':
    include:
      - '^feat:'
    exclude: [ ]
  'type: test':
    include:
      - '^test:'
    exclude: [ ]
  'type: sustainging':
    include:
      - '^revert:'
    exclude: [ ]