spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
      jdbc-url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
  hazelcast:
    config: classpath:hazelcast/hazelcast-config-real.xml
server:
  port: 1234


#test: value is present