name: add-labels
on:
  pull_request:
    types: [ opened ]

jobs:

  labeler:
    runs-on: [ sso-runner ]

    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
