name: echo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  echo:
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Set up JDK 1.11
          uses: actions/setup-java@v3
          with:
            java-version: '11'

